# Generated by Django 4.1.3 on 2022-11-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('population', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diseasetype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'diseasetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('cname', models.ForeignKey(db_column='cname', on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.country')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mysite.users')),
                ('degree', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publicservant',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mysite.users')),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'publicservant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.diseasetype')),
            ],
            options={
                'db_table': 'disease',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mysite.diseasetype')),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.doctor')),
            ],
            options={
                'db_table': 'specialize',
                'managed': True,
                'unique_together': {('id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('cname', models.OneToOneField(db_column='cname', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mysite.country')),
                ('first_enc_date', models.DateField()),
                ('disease_code', models.ForeignKey(db_column='disease_code', on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.disease')),
            ],
            options={
                'db_table': 'discover',
                'managed': True,
                'unique_together': {('cname', 'disease_code')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mysite.publicservant')),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('cname', models.ForeignKey(db_column='cname', on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.country')),
                ('disease_code', models.ForeignKey(db_column='disease_code', on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.disease')),
            ],
            options={
                'db_table': 'record',
                'managed': True,
                'unique_together': {('email', 'cname', 'disease_code')},
            },
        ),
    ]
