# Generated by Django 4.1.3 on 2022-11-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='discover',
            options={'managed': False, 'verbose_name': 'Discover', 'verbose_name_plural': 'Discoveries'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'managed': False, 'verbose_name': 'Disease', 'verbose_name_plural': 'Diseases'},
        ),
        migrations.AlterModelOptions(
            name='diseasetype',
            options={'managed': False, 'verbose_name': 'Disease Type', 'verbose_name_plural': 'Disease Types'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False, 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='publicservant',
            options={'managed': False, 'verbose_name': 'Public Servant', 'verbose_name_plural': 'Public Servants'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'managed': False, 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterModelOptions(
            name='specialize',
            options={'managed': False, 'verbose_name': 'Specialize', 'verbose_name_plural': 'Specializes'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
